version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ml-extractor-backend:latest
    ports:
      - "8010:8010"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./config_admin.json:/app/config_admin.json:rw

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: "http://backend:8010"
    image: ml-extractor-frontend:latest
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:8010
