services:
  - type: web
    name: ml-extractor
    env: python
    branch: pyinstaller-artifacts
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: >
      gunicorn -k uvicorn.workers.UvicornWorker simple_backend:app --bind 0.0.0.0:$PORT --log-level info
    envVars:
      - key: CORS_ORIGINS
        value: "https://your-render-domain.example"
    healthCheckPath: /api/health
    autoDeploy: true

  - type: static
    name: ml-extractor-frontend
    env: static
    branch: pyinstaller-artifacts
    plan: free
    region: oregon
    # Build the frontend (if dependencies exist) and publish the built files
    buildCommand: >
      bash -lc "if [ -f frontend/package.json ]; then cd frontend && npm ci && npm run build && cd ..; fi"
    publishPath: frontend/dist
    autoDeploy: true
