columns:
  SKU: SKU
  Name: Product Name
  Price: Price
  Description: Description
  # Add more mappings as needed

template:
  - title
  - price
  - description
  - stock
  - category
  - image_url
  - brand

mapping:
  title: title
  price: price
  description: description
  stock: stock
  category: category
  image_url: image_url
  brand: brand
