name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt || pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -q

      - name: Upload pytest results (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-logs
          path: ./.pytest_cache
          if-no-files-found: ignore
