name: Compile check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install lightweight deps
        run: |
          python -m pip install flask requests

      - name: Compile passenger_wsgi.py
        run: python -m compileall passenger_wsgi.py

      - name: Compile full repository
        run: python -m compileall .

      - name: Run small smoke test (app_flask)
        run: |
          python - <<'PY'
          from app_flask import app
          c = app.test_client()
          resp = c.get('/')
          print('status:', resp.status_code)
          if resp.status_code not in (200,302):
              raise SystemExit('smoke test failed with status ' + str(resp.status_code))
          print('smoke test passed')
          PY

      - name: Test passenger_wsgi import (default)
        run: |
          python - <<'PY'
          import importlib, traceback
          try:
              m = importlib.import_module('passenger_wsgi')
              app = getattr(m, 'application', None)
              print('passenger_wsgi loaded, application:', type(app))
          except Exception:
              print('passenger_wsgi import failed:')
              traceback.print_exc()
              raise
          PY

      - name: Test passenger_wsgi import (with USE_FALLBACK=1)
        env:
          USE_FALLBACK: '1'
        run: |
          python - <<'PY'
          import importlib, os, traceback
          try:
              # ensure env var seen by module-level code
              os.environ['USE_FALLBACK'] = '1'
              importlib.reload(importlib.import_module('passenger_wsgi'))
              m = importlib.import_module('passenger_wsgi')
              app = getattr(m, 'application', None)
              print('passenger_wsgi loaded with USE_FALLBACK=1, application:', type(app))
          except Exception:
              print('passenger_wsgi import with USE_FALLBACK=1 failed:')
              traceback.print_exc()
              raise
          PY
